crypto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('account.urls', namespace='account')),
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('profile/', profile, name="profile"),
    path('deposit/', deposit, name="deposit"),
    path('deposit/btc/', deposit_btc, name="btc"),
    path('deposit/eth/', deposit_eth, name="eth"),
    path('deposit/trc/', deposit_trc, name="trc"),
    path('withdraw/', withdraw, name="withdraw"),
    path('wallet/', wallet, name="wallet"),
    path('wallet/<int:pk>/delete/', del_wallet, name="del_wallet"),
    path('referrals/', my_referrals, name="referral"),
    path('logout/', logout_request, name="logout"),
    path('deposit/?a=total/', tot_deposit, name="tot_deposit"),
    path('withdraw/?a=total/', tot_withdraw, name="tot_withdraw"),
]

main/urls.py
import imp
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('privacy/', privacy, name="privacy"),
    path('terms/', terms, name="terms"),
    path('contact/', contact, name="contact"),
    path('services/', services, name="services"),
    path('plans/', plans, name="plans"),
    path('legal/', legal, name="legal"),
    path('how-to-invest/', howto, name="howto"),
] 

dashboard/models.py
from django.db import models, transaction
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.db.models import F
import re
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from crypto import settings
from .tasks import activate_subscription

# Custom user
user = get_user_model()

class Plan(models.Model):
    SUB_PLAN = (
        ('Basic', 'Basic Plan'),
        ('Gold', 'Gold Plan'),
        ('Platinum', 'Platinum Plan')
    )
    plan_name = models.CharField(max_length=8, choices=SUB_PLAN)
    percent = models.PositiveIntegerField()
    ref_bonus = models.PositiveIntegerField(default=10)
    min = models.DecimalField(max_digits=10, decimal_places=2)
    max = models.DecimalField(max_digits=10, decimal_places=2)
    calc_percent = models.DecimalField(max_digits=10, editable=False, decimal_places=2, default=100.00, verbose_name='Percentage Formula')
    duration = models.PositiveIntegerField()

    def __str__(self):
        return self.plan_name


class Subscription(models.Model):
    SUB_METHOD = (
        ('Account', 'Account Balance'),
        ('Wallet', 'Wallet')
    )
    SUB_CURRENCY = (
        ('Btc', 'Bitcoin - BTC'),
        ('Eth', 'Ethereum - ETH'),
        ('Trc20', 'Tether - USDT(TRC20)')
    )
    SUB_STATUS =(
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Expired', 'Expired')
    ) 
    user = models.ForeignKey(user, on_delete=models.CASCADE, related_name="user")
    type = models.CharField(max_length=10, default="Deposit", editable=False)
    plan = models.ForeignKey(Plan, on_delete=models.DO_NOTHING, related_name="plan")
    sub_method = models.CharField(max_length=24, choices=SUB_METHOD, default='Account')
    sub_currency = models.CharField(max_length=12, choices=SUB_CURRENCY, default='Btc')
    sub_amount = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    expires_at = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=9, choices=SUB_STATUS, default="Pending")
    verified_on = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=False)
    initiated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Username: {self.user.username.capitalize()} || Plan: {self.plan.plan_name}\
             || Status: {self.status} || Balance: ${self.user.balance}"

    def clean(self):
        """SUBSCRIPTION CUSTOM VALIDATION"""
        # Don't allow amount out of the Basic plan range
        if self.plan.plan_name == "Basic":
            if self.sub_amount < self.plan.min or self.sub_amount > self.plan.max:
                raise ValidationError({'sub_amount': _(f"Enter an amount within the range of ${self.plan.min} and ${self.plan.max}")})
            # Validate Account Balance
            if self.sub_method == "Account":
                if self.sub_amount > self.user.balance:
                    raise ValidationError({'sub_amount': _(f"Insufficient balance. Kindly recharge via your wallet")})
        # Don't allow amount out of the Advanced plan range
        elif self.plan.plan_name == "Gold":
            if self.sub_amount < self.plan.min or self.sub_amount > self.plan.max:
                raise ValidationError({'sub_amount': _(f"Enter an amount within the range of ${self.plan.min} and ${self.plan.max}")})
            # Validate Account Balance
            if self.sub_method == "Account":
                if self.sub_amount > self.user.balance:
                    raise ValidationError({'sub_amount': _(f"Insufficient balance. Kindly recharge via your wallet")})
        # Don't allow amount out of the Platinum plan range
        else:
            if self.sub_amount < self.plan.min or self.sub_amount > self.plan.max:
                raise ValidationError({'sub_amount': _(f"Enter an amount within the range of ${self.plan.min} and ${self.plan.max}")})
            # Validate Account Balance
            if self.sub_method == "Account":
                if self.sub_amount > self.user.balance:
                    raise ValidationError({'sub_amount': _(f"Insufficient balance. Kindly recharge via your wallet")})

    @classmethod
    def update_active_bal(cls, sender, instance, *args, **kwargs):
        """Update user account bal. after payment confirmation"""
        user=instance.user
        if instance.sub_method == "Account":
            user.balance = F('balance') - instance.sub_amount
            user.save()

    @classmethod
    def activate_subscription(cls, sender, instance, *args, **kwargs):
        """Start the countdown"""
        user=instance.user
        if instance.active:
            # TODO: SEND CONFIRMATION MAIL
            context = ({
                'user': user.username,
            })
            html_version = './dashboard/mails/active_dep.html'
            html_message = render_to_string(html_version, context)
            subject = 'xandcoin - Deposit Approved'
            message = EmailMessage(subject, html_message, settings.EMAIL_HOST_USER, [user.email])
            message.content_subtype = 'html'
            message.send(fail_silently=True)

            # Let celery handle the logic asynchronously
            transaction.on_commit(lambda: activate_subscription.apply_async(args=(instance.pk,)))
                
post_save.connect(Subscription.update_active_bal, sender=Subscription)
post_save.connect(Subscription.activate_subscription, sender=Subscription)
        

class Wallet(models.Model):
    NETWORK = (
        ('Btc', 'Bitcoin - BTC'),
        ('Eth', 'Ethereum - ETH'),
        ('Trc20', 'Tether - USDT(TRC20)')
    )
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, choices=NETWORK, verbose_name="Wallet name")
    address = models.CharField(max_length=60, verbose_name="Wallet address")

    class Meta:
        verbose_name_plural = 'Wallet Address'
        unique_together = ('user', 'type')

    def __str__(self):
        return f"{self.get_type_display()} - {self.address}" 

    def clean(self):
        """WALLET ADDRESS CUSTOM VALIDATION"""
        if not self and not self.required:
            return None

        # BITCOIN WALLET
        if self.type == "Btc":
            if not self.address.startswith("1") and not self.address.startswith('3') and not self.address.startswith('bc1'):
                raise ValidationError({'address': _(f"Invalid Bitcoin address.")})
            if "\n" in self.address:
                raise ValidationError({'address': _(f"Multiple lines in the Bitcoin address.")})
            if " " in self.address:
                raise ValidationError({'address': _(f"Spaces in the Bitcoin address.")})
            if re.match(r"[a-zA-Z1-9]{26,35}$", self.address) is None:
                raise ValidationError({'address': _(f"Invalid Bitcoin address.")})
        # ETHEREUM WALLET
        elif self.type == "Eth":
            if not self.address.startswith('0x'):
                raise ValidationError({'address': _(f"Invalid Ethereum address.")})
            if len(self.address) != 42:
                raise ValidationError({'address': _(f"Invalid Ethereum address.")})
            if "\n" in self.address:
                raise ValidationError({'address': _(f"Multiple lines in the Ethereum address.")})
            if " " in self.address:
                raise ValidationError({'address': _(f"Spaces in the Ethereum address.")})
        # USDT WALLET
        else:
            if not self.address.startswith("T"):
                raise ValidationError({'address': _(f"Invalid USDT address.")})
            if len(self.address) != 34:
                raise ValidationError({'address': _(f"Invalid USDT address.")})
            if "\n" in self.address:
                raise ValidationError({'address': _(f"Multiple lines in the USDT address.")})
            if " " in self.address:
                raise ValidationError({'address': _(f"Spaces in the USDT address.")})


class Withdrawal(models.Model):
    WITHDRAW_STATUS = (
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Completed', 'Completed')
    ) 
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, on_delete=models.SET_NULL, null=True, verbose_name="Withdrawal wallet")
    type = models.CharField(max_length=10, default="Withdrawal", editable=False)
    amount =models.DecimalField(max_digits=1000, decimal_places=2, default=0.00, verbose_name="Withdrawal amount")
    min_withdraw = models.DecimalField(max_digits=1000, decimal_places=2, default=80.00, verbose_name='Minimum withdrawal')
    status = models.CharField(max_length=12, choices=WITHDRAW_STATUS, default="Pending", verbose_name="Withdrawal status")
    verified_on = models.DateTimeField(blank=True, null=True)
    initiated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Username: {self.user.username.capitalize()} || Status: {self.status} || Balance: {self.user.balance}"

    def clean(self):
        """WITHDRAWAL CUSTOM VALIDATION"""
        if self.amount > self.user.balance:
            raise ValidationError({'amount': _(f"Withdrawal failed. Insufficient balance.")})
        if self.amount < self.user.balance and self.amount < self.min_withdraw:
            raise ValidationError({'amount': _(f"Withdrawal failed. Minimum withdrawal amount is ${self.min_withdraw}")})

    @classmethod
    def confirm_withdrawal(cls, sender, instance, *args, **kwargs):
        """
        Update user account bal. after payment confirmation
        and send confirmation mail to the user
        """
        user=instance.user
        if instance.status == "Confirmed":
            user.balance = F('balance') - instance.amount
            user.save()

dashboard/templates/dashboard/deposit/base.html
{% extends 'dashboard/base.html' %}
{% load static %}

    <!-- TITLE -->
    {% block title %}
        beeLabbs | Dashboard | Deposit
    {% endblock title %}

    <!-- HEADING -->
    {% block heading %}
        DEPOSIT
    {% endblock heading %}
    
    <!-- MAIN CONTENT -->
    {% block content %}
        <section class="summary px-lg-5 px-3 py-4">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="card bg-transparent">
                        <div class="card-body">
                            <h1 class="text-center">Hi {% block name %} {% endblock %}!</h1>
                            <p>
                                You initiated a deposit request. Kindly make a deposit of 
                                <span style="color: rgb(39, 179, 252);"> <b>${% block amount %}{% endblock %}
                                </b> </span> to the Company's Address below.
                            </p>
                            <p></p>
                            <div style="display: flex;" class="dep-wal">
                                <input type="text" class="form-control form-control-sm" value="{% block value %}{% endblock %}" readonly>
                                <button class="btn-sm btn btn-primary">Copy</button>
                            </div>
                            <!-- <textarea name="" id="" cols="" class="w-100" rows=""></textarea> -->
                            <small>This address accepts only <b>{% block currency %}{% endblock %}</b></small>
                            <p></p>
                            <p>Your chosen plan is: <b>{% block plan %}{% endblock %}</b></p>
                            <p>Your account will be automatically activated once your payment is verified on the BlockChain network.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        <style>
            footer {display: none;}

            .dep-wal input {
                background: lightslategrey;
                color: #000 !important;
                letter-spacing: 0.5px;
                border: 0;
                border-top-right-radius: 0;
                border-bottom-right-radius: 0;
            }

            .dep-wal input:focus {
                background: lightslategrey;
            }

            .dep-wal .btn-primary {
                border-top-left-radius: 0;
                border-bottom-left-radius: 0;
            }
        </style>
    {% endblock content %}
        

dashboard/templates/dashboard/deposit/btc.html
{% extends 'dashboard/deposit/base.html' %}

{% block name %}{{ plan.user.username|title }}{% endblock %}
{% block amount %}{{ plan.sub_amount }}{% endblock %}
{% block currency %}{{ plan.get_sub_currency_display }}{% endblock %}
{% block plan %}{{ plan.plan.plan_name }}{% endblock %}
{% block value %}{% endblock %}

dashboard/templates/dashboard/deposit/eth.html
{% extends 'dashboard/deposit/base.html' %}

{% block name %}{{ plan.user.username|title }}{% endblock %}
{% block amount %}{{ plan.sub_amount }}{% endblock %}
{% block currency %}{{ plan.get_sub_currency_display }}{% endblock %}
{% block plan %}{{ plan.plan.plan_name }}{% endblock %}
{% block value %}{% endblock %}

dashboard/templates/dashboard/deposit/trc.html
{% extends 'dashboard/deposit/base.html' %}

{% block name %}{{ plan.user.username|title }}{% endblock %}
{% block amount %}{{ plan.sub_amount }}{% endblock %}
{% block currency %}{{ plan.get_sub_currency_display }}{% endblock %}
{% block plan %}{{ plan.plan.plan_name }}{% endblock %}
{% block value %}{% endblock %}