account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('signup/<str:ref_code>/', register, name="register"),
    path('signup/', register, name="register"),
    path('login/', login_request, name="login"), 
    path('dashboard/password-change/', security, name="security"),
    path('password_reset/', reset_password, name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html', success_url='/login/'), name='password_reset_confirm'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('account.urls', namespace='account')),
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('profile/', profile, name="profile"),
    path('deposit/', deposit, name="deposit"),
    path('deposit/btc/', deposit_btc, name="btc"),
    path('deposit/eth/', deposit_eth, name="eth"),
    path('deposit/trc/', deposit_trc, name="trc"),
    path('withdraw/', withdraw, name="withdraw"),
    path('wallet/', wallet, name="wallet"),
    path('wallet/<int:pk>/delete/', del_wallet, name="del_wallet"),
    path('referrals/', my_referrals, name="referral"),
    path('logout/', logout_request, name="logout"),
    path('deposit/?a=total/', tot_deposit, name="tot_deposit"),
    path('withdraw/?a=total/', tot_withdraw, name="tot_withdraw"),
]

main/urls.py
import imp
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('privacy/', privacy, name="privacy"),
    path('terms/', terms, name="terms"),
    path('contact/', contact, name="contact"),
    path('services/', services, name="services"),
    path('plans/', plans, name="plans"),
    path('legal/', legal, name="legal"),
    path('how-to-invest/', howto, name="howto"),
] 

main/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse


class ContactForm(forms.Form):
    name = forms.CharField(max_length=30, required=True,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'name',
                                'placeholder': 'Name *'
                            }))
    email = forms.EmailField(max_length=30, required=True,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'email',
                                'placeholder': 'Email *'
                            }))
    subject = forms.CharField(required=True, max_length=20,
                             widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'subject',
                                'placeholder': 'Subject *'
                            }))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={
                                'class':'form-control form-control-sm',
                                'id': 'message',
                                'rows': 5,
                                'placeholder': 'Message *'
                            }))

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()
        name = cl_data.get('name').strip()
        email = cl_data.get('email')
        subject = cl_data.get('subject')
        # Compose mail
        message = f'{name.capitalize()} with email {email} just sent you a mail.\n'
        message += f"\nSubject: '{subject}'\n\n"
        message += cl_data.get('message')
        message += f'\n\n\nXendcoin ContactUs Page'
        message += f"\nxendcoin.com"
        # Return composed mail data
        return subject, message

    def send(self):
        subject, message = self.get_info()
        try:
            send_mail(
                subject=subject,
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=['okonkwogodspower@yahoo.com'],
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

dashboard/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from dashboard.models import Subscription, Withdrawal, Wallet
from .forms import (BasicInfo, AddressInfo, DeleteAccount, 
                    DepositForm, WalletForm, WithdrawalForm)
from django.utils.translation import gettext_lazy as _
# from django.db.models import F, Sum
from account.models import Referral
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from crypto import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

UserModel = get_user_model()

# Create your views here.
@login_required(login_url='account:login')
def dashboard(request):
    user = UserModel.objects.get(pk=request.user.pk)
    last_deposit = Subscription.objects.filter(user=user, active=True).last()
    last_withdrawal = Withdrawal.objects.filter(user=user, status="Confirmed").last()
    deposit = Subscription.objects.all()
    withdrawal = Withdrawal.objects.all()
    # TOTAL DEPOSITS
    tot_deposit = sum([i.sub_amount for i in deposit if i.user==user and i.active==True])
    # ACTIVE DEPOSITS
    active_deposit = sum([i.sub_amount for i in deposit if i.user==user and i.status=="Confirmed"])
    # TOTAL WITHDRAWALS
    tot_withdraw = sum([i.amount for i in withdrawal if i.user==user and i.status=="Confirmed"])
    # PENDING WITHDRAWALS
    pend_withdraw = sum([i.amount for i in withdrawal if i.user==user and i.status=="Pending"])
    # TOTAL BALANCE
    total_balance = user.balance
    # EARNED PROFIT TOTAL
    earned_total = user.profit

    context = {
        'tot_bal': total_balance,
        'tot_earned': earned_total,
        'last_deposit': last_deposit,
        'tot_deposit': tot_deposit,
        'active_deposit': active_deposit,
        'last_withdraw': last_withdrawal,
        'pend_withdraw': pend_withdraw,
        'tot_withdraw': tot_withdraw,
    }
    return render(request, 'dashboard/dashboard.html', context)

@login_required(login_url='account:login')
def profile(request):
    """Update User's Profile"""
    basic_info = BasicInfo(instance=request.user)
    address_info = AddressInfo(instance=request.user)
    delete_account = DeleteAccount(instance=request.user)
    if request.method == 'POST':
        if "form1" in request.POST:
            basic_info = BasicInfo(request.POST, instance=request.user)
            if basic_info.is_valid():
                basic_info.save()
                messages.success(request, ("Your <b>Basic info</b> has been updated!"))
                return redirect('dashboard:profile')
        if 'form2' in request.POST:   
            address_info = AddressInfo(request.POST, instance=request.user)
            if address_info.is_valid():
                address_info.save()
                messages.success(request, ("Your <b>Address info</b> has updated!"))
                return redirect('dashboard:profile')
        if 'form3' in request.POST:
            delete_account = DeleteAccount(request.POST, instance=request.user)
            if delete_account.is_valid():
                deactivate_user = delete_account.save(commit=False)
                del_user = delete_account.cleaned_data['del_account']
                deactivate_user.save()
                if del_user:
                    messages.info(request, ("Your account has been deactivated. \n \
                                            Contact us for reactivation."))   
                    # SEND MAIL    
                    return redirect('main:contact')
    context = {
        'basic_info': basic_info,
        'address_info': address_info,
        'delete_account': delete_account
    }
    return render(request, 'dashboard/profile.html', context)

# Helper Function
def get_ip_address(request):
    """Function to get user's ip address"""
    user_ip_address = request.META.get('HTTP_X_FORWARDED_FOR')
    if user_ip_address:
        ip = user_ip_address.split(',')[0].strip()
    else:
        ip = request.META.get('REMOTE_ADDR', None)
    return ip


@login_required(login_url='account:login')
def deposit(request):
    """Function to allow investors make deposit"""
    user = get_object_or_404(UserModel, pk=request.user.pk)
    subscription = Subscription(user=user)
    if request.method == 'POST':
        form = DepositForm(request.POST,instance=subscription)
        if form.is_valid():
            subscribe = form.save(commit=False)
            method = form.cleaned_data['sub_method']
            currency = form.cleaned_data['sub_currency']
            amount = form.cleaned_data['sub_amount']
            if method == "Account":
                subscribe.active = True
                subscribe.save()
                messages.success(request, ("Transaction Successful!"))
                return redirect('dashboard:dashboard')
            else:
                subscribe.save()
                # TODO: SEND CONFIRMATION MAIL TO USER
                name = user.username
                context = ({
                    'user': name,
                    'amount': amount,
                    'currency': currency
                })
                html_version = './dashboard/mails/inactive_dep.html'
                html_message = render_to_string(html_version, context)
                subject = 'xandcoin - Deposit Request'
                message = EmailMessage(subject, html_message, settings.EMAIL_HOST_USER, [user.email])
                message.content_subtype = 'html'
                message.send(fail_silently=True)
                # TODO: SEND CONFIRMATION MAIL TO ADMIN
                admin_msg = f'Hello Admin,\n\n{name.capitalize()} just initiated a deposit request of ${amount} via {subscription.get_sub_currency_display()}.'
                admin_msg += f'\n\nKindly keep an eye out for the deposit, and confirm the transaction in the admin portal.'
                admin_msg += f'\nTo do that, navigate to the Subscription table, click on the user and toggle on the active button.'
                admin_msg += f'\n\nRegards,\nDevTeam.'
                message1 = EmailMessage(
                    subject = f"User Deposit Notification",
                    body = admin_msg,
                    from_email = 'settings.EMAIL_HOST_USER',
                    to = ['okonkwogodspower@yahoo.com'],
                )
                message1.send(fail_silently=True)

                if currency == "Btc":
                    return redirect('dashboard:btc')
                elif currency == "Eth":
                    return redirect('dashboard:eth')
                else:
                    return redirect('dashboard:trc')
    else:
        form = DepositForm(instance=user)
    context = {
        'form': form,
    }
    return render(request, 'dashboard/deposit.html', context)


@login_required(login_url='account:login')
def deposit_btc(request):
    user = request.user
    plan = Subscription.objects.filter(user=user, sub_currency="Btc" ).last()
    context = {'plan': plan}
    return render(request, 'dashboard/deposit/btc.html', context)


@login_required(login_url='account:login')
def deposit_eth(request):
    user = request.user
    plan = Subscription.objects.filter(user=user, sub_currency="Eth" ).last()
    context = {'plan': plan}
    return render(request, 'dashboard/deposit/eth.html', context)


@login_required(login_url='account:login')
def deposit_trc(request):
    user = request.user
    plan = Subscription.objects.filter(user=user, sub_currency="Trc20" ).last()
    context = {'plan': plan}
    return render(request, 'dashboard/deposit/trc.html', context)


@login_required(login_url='account:login')
def withdraw(request):
    user=request.user
    withdraw = Withdrawal(user=user)
    if request.method == 'POST':
        form = WithdrawalForm(request.POST, instance=withdraw, user=user)
        if form.is_valid():
            form.save()
            amount = form.cleaned_data['amount']
            wallet = form.cleaned_data['wallet']
            name = user.username
            # TODO: SEND CONFIRMATION MAIL TO USER
            context = ({
                'user': name,
                'amount': amount,
                'wallet': wallet.type,
                'address': wallet.address
            })
            html_version = './dashboard/mails/inactive_with.html'
            html_message = render_to_string(html_version, context)
            subject = 'xandcoin - Withdrawal Request'
            message = EmailMessage(subject, html_message, settings.EMAIL_HOST_USER, [user.email])
            message.content_subtype = 'html'
            message.send(fail_silently=True)
            # TODO: SEND CONFIRMATION MAIL TO ADMIN
            admin_msg = f'Hello Admin,\n\n{name.capitalize()} just initiated a withdrawal request.'
            admin_msg += f"\n\nKindly review the withdrawal request. And, if everything seems okay, "
            admin_msg += f"send the required amount to {name.capitalize()} specified address."
            admin_msg += f"\n\nAmount: ${amount}.00\nWallet type: {wallet.get_type_display()}\nWallet address: {wallet.address}"
            admin_msg += f"\n\nOnce that is done, confirm the transaction via the admin panel."
            admin_msg += f"\nTo do that, navigate to the Withdrawal table, click on the user and change the status from 'Pending' to 'Confirmed'."
            admin_msg += f'\n\nRegards,\nDevTeam.'
            message1 = EmailMessage(
                subject = f"User Withdrawal Notification",
                body = admin_msg,
                from_email = 'settings.EMAIL_HOST_USER',
                to = ['okonkwogodspower@yahoo.com'],
            )
            message1.send(fail_silently=True)

main/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from dashboard.models import Subscription, Withdrawal
from .forms import ContactForm

# Create your views here.
def home(request):
    sub = Subscription.objects.all()[:10]
    withdraw = Withdrawal.objects.all()[:10]
    context = {
        'sub': sub,
        'withdraw': withdraw
    }
    return render(request, 'main/index.html', context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send()
            messages.success(request, ('Thank you for contacting us. Our team will reach out to you soon.'))
            return redirect('main:contact')
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'main/contact.html', context)


def plans(request):
    return render(request, 'main/plans.html')

def about(request):
    return render(request, 'main/about.html')

def faq(request):
    return render(request, 'main/faq.html')

def privacy(request):
    return render(request, 'main/privacy.html')

def terms(request):
    return render(request, 'main/terms.html')

def services(request):
    return render(request, 'main/services.html')

def howto(request):
    return render(request, 'main/howto.html')

def legal(request):
    return render(request, 'main/legal.html')

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            
        {% endblock title %}
            
    </title>

    <!-- Theme Style + Bootstrap -->
    <link rel="shortcut icon" href="{% static 'img/icon-1.ico' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/theme.min.css' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/boxicons.min.css' %}">
    

    <!-- ============================================================== -->
    <!--      This template was developed by beeLabbs tech hub          -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!--     Disclaimer: www.beeLabbs.com/terms/#disclaimer             -->
    <!-- ============================================================== -->
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg">
            <div class="container d-flex justify-content-between">
                <a href="{% url 'main:home' %}" class="navbar-brand my-0 py-0">
                    <img src="{% static 'img/site-logo-1.png' %}" style="height: 50px;"  alt="">
                    <span style="color: rgba(10, 202, 151, 0.788);">Xendcoin</span>
                </a>
                    
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a href="{% url 'dashboard:logout' %}" class="nav-link btn text-light btn-primary">
                            <i class="bx bx-user fs-lg me-2"> Log Out</i>
                        </a>
                    </li>
                </ul>
            </div>   
        </nav>
    </header>

    <main class="page-wrapper mb-5" style="padding-bottom: 40px !important;">
        <!-- Main Nav -->
        <section class="px-lg-5 px-0" style="padding-top: 1em; box-shadow: 0 1px 6px rgba(0, 0, 0, 0.664);">
            <nav class="navbar navbar-expand-lg justify-content-center">
                <button class="navbar-toggler" type="button" 
                    data-bs-toggle="collapse" data-bs-target="#navmenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
            

                <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav mx-auto main-nav justify-content-center" style="flex-wrap: wrap;">
                        <li class="nav-item">
                            <a href="{% url 'dashboard:dashboard' %}" class="nav-link text-light main">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:deposit' %}" class="nav-link text-light main">Deposit</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:withdraw' %}" class="nav-link text-light main">Withdraw</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-light main" 
                            data-bs-toggle="dropdown" role="button" aria-haspopup="true" 
                            aria-expanded="false">Transactions</a>
                            <ul class="dropdown-menu text-light" style="background: rgb(1, 1, 36); border: 0;">
                                <li>
                                    <a href="{% url 'dashboard:tot_deposit' %}" class="dropdown-item text-light">Deposits</a>
                                </li>
                                <li>
                                    <a href="{% url 'dashboard:tot_withdraw' %}" class="dropdown-item text-light">Withdrawals</a>
                                </li>
                                <!-- <li>
                                    <a href="{% url 'main:services' %}" class="dropdown-item text-light">Bonuses</a>
                                </li> -->
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:referral' %}" class="nav-link text-light main">Referrals</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'dashboard:profile' %}" class="nav-link text-light main">Profile</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </section>

        <section class="row">
            <div class="col-md-6 offset-md-3">
                {% include 'dashboard/includes/messaging.html' %}
            </div>
        </section>

        <!-- Welcome -->
        <section class="px-lg-5 px-3 py-3">
            <div class="row">
                <div class="col-md-6"> 
                    {% if user.is_authenticated %}
                        <p class="h3" style="font-weight: 100;">
                            Welcome back, <b>{{ user.username|title }}</b>
                        </p>
                    {% else %}
                        <p class="h3" style="font-weight: 100;">
                            Welcome back!
                        </p>
                    {% endif %}
                    <hr style="color: grey;">
                    <div class="d-flex mt-1">
                        <p style="padding-right: 20px;">HOME</p>
                        <P>
                            <i class="bx bx-user"></i>
                            <span style="color: rgb(10, 223, 165);">   
                                {% block heading %}
                                    
                                {% endblock heading %}
                            </span>
                        </P>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="affiliate-link">
                        <div class="pt-3 px-4 pb-2">
                            Your Personal Affiliate Link:
                        </div>
                        <hr style="margin-left: 22px; color: grey;">
                        
                        <div>
                            <p class="pb-2 px-4 pt-2" style="color: rgb(39, 179, 252);">
                                <span style="padding-right: 5px;">http://13.40.240.230/signup/{{ request.user.referral.code }}</span>
                                <span class="btn btn-sm btn-primary" style="padding:0 20px; height: 30px;">Copy</span>
                            </p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </section>
        
        {% block content %}
            
        {% endblock content %}    
    </main>

    <footer class="py-2 fixed-bottom">
        <section class="container">
            <div class="currencies d-flex justify-content-between">
                <div class="currency px-2">
                    <img src="{% static 'img/icons/bitcoin.png' %}" class="coin" alt="btc">
                    <span class="coin">bitcoin</span>
                    <span class="price bitCoin"></span>
                </div>
                <div class="currency px-2">
                    <img src="{% static 'img/icons/ethereum.png' %}" alt="btc" style="padding-right: 10px;">
                    <span class="coin">ethereum</span>
                    <span class="price ethCoin"></span>
                </div>
                <div class="currency px-2">
                    <img src="{% static 'img/icons/litecoin.png' %}" alt="btc" style="padding-right: 10px;">
                    <span class="coin">litecoin</span>
                    <span class="price ltcCoin"></span>
                </div>
                <div class="currency px-2">
                    <img src="{% static 'img/icons/dogecoin.png' %}" alt="btc" style="padding-right: 10px;">
                    <span class="coin">dogecoin</span>
                    <span class="price dogeCoin"></span>
                </div>
            </div>
        </section>
    </footer>


    <script type="text/javascript">
        // Query Binance API to get latest crypto prices
        const key  = 'https://www.binance.com/api/v3/ticker/price?symbols='
        const currencies = '%5B%22BTCUSDT%22,%22ETHUSDT%22,%22LTCUSDT%22,%22DOGEUSDT%22%5D'
        const url = key + currencies
        // Make the API call request
        fetch(url)
        .then((response) => {
            return response.json()
        })
        .then((data) => {
            let crypto = data;
            // Convert the prices to float and round to two d.p
            let btc = parseFloat(crypto[0].price).toFixed(2);
            let eth = parseFloat(crypto[1].price).toFixed(2);
            let ltc = parseFloat(crypto[2].price).toFixed(2);
            let doge = parseFloat(crypto[3].price).toFixed(4);
            // Append the prices to the main content
            document.querySelector('.bitCoin').textContent = '$' + btc;
            document.querySelector('.ethCoin').textContent = '$' + eth;
            document.querySelector('.ltcCoin').textContent = '$' + ltc;
            document.querySelector('.dogeCoin').textContent = '$' + doge;
        })
        .catch((error) => {
            console.log(error)
        })
    </script>

     <!-- Vendor Scripts -->
     <script src="{% static 'js/theme.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
     <script src="{% static 'js/smooth-scroll.polyfills.min.js' %}"></script>
</body>
</html>

dashboard/templates/dashboard/referral.html
{% extends 'dashboard/base.html' %}
{% load static %}

    <!-- TITLE -->
    {% block title %}
        beeLabbs | Dashboard | Transactions
    {% endblock title %}

    <!-- HEADING -->
    {% block heading %}
        TRANSACTIONS
    {% endblock heading %}
    
    <!-- MAIN CONTENT -->
    {% block content %}
        <!-- TRANSACTIONS -->
        <section class="summary px-lg-5 px-3 py-3" style="padding-bottom: 60px !important;">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <p><strong style="color:rgb(10, 223, 165); font-size: 18px;">
                        My Referrals
                    </strong> <br>
                    <small>
                        Share your link with your friends and earn a percentage on their first deposit
                    </small>
                    </p>
                    <!-- TODO: DISPLAY THE REF CODE OF THE USER -->

                    <!-- Dark table with striped rows -->
                    <div class="table-responsive">
                        <table class="table table-dark table-striped">
                            <thead class="tot-head">
                                <tr>
                                <th>S/N</th>
                                <th>Referral</th>
                                <th>Bonus</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if not referrals %}
                                    <tr class="tot-row">
                                        <td><em>No data to display at the moment.</em></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% else %}
                                    {% for i in referrals %}
                                        <tr class="tot-row">
                                            <td class="text-light">{{ forloop.counter }}.</td>
                                            <td class="text-light">{{ i.user|title }}</td>
                                            <td class="text-light">${{ i.bonus }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <!-- Pagination -->
                <div class="d-flex justify-content-center pt-3">
                    {% include 'dashboard/includes/pagination.html' with page=referrals %}
                </div>
            </div>           
        </section>

    {% endblock content %}        

dashboard/templates/dashboard/settings.html
{% extends 'dashboard/base.html' %}

    <!-- TITLE -->
    {% block title %}
        
    {% endblock title %}

    <!-- HEADING -->
    {% block heading %}
        PROFILE
    {% endblock heading %}


{% block content%}
    <section class="account px-lg-5 px-3 py-2">
        <div class="row">
            <!-- Sidebar (User info + Account menu) -->
        <aside class="col-lg-3 col-md-4 border-end pb-5 mt-n1">
            <div class="position-sticky top-0">
            <div class="text-center pt-3">
                <h2 class="h5 mb-1">{{ user.first_name|title }} {{ user.last_name|title }}</h2>
                <p class="mb-3 pb-3">{{ user.email }}</p>
                <button type="button" class="btn btn-secondary w-100 d-md-none mt-n2 mb-3 profile-side-menu" 
                data-bs-toggle="collapse" data-bs-target="#profile-menu">
                <i class="bx bxs-user-detail fs-xl me-2"></i>
                Profile menu
                <i class="bx bx-chevron-down fs-lg ms-1"></i>
                </button>
                <div id="profile-menu" class="list-group list-group-flush collapse d-md-block">
                <a href="{% url 'dashboard:profile' %}" class="prof list-group-item list-group-item-action d-flex align-items-center">
                    <i class="bx bx-cog fs-xl opacity-60 me-2"></i>
                    Account Details
                </a>
                <a href="{% url 'account:security' %}" class="prof list-group-item list-group-item-action d-flex align-items-center">
                    <i class="bx bx-lock-alt fs-xl opacity-60 me-2"></i>
                    Security
                </a>
                <a href="{% url 'dashboard:wallet' %}" class="prof list-group-item list-group-item-action d-flex align-items-center">
                    <i class="bx bx-bell fs-xl opacity-60 me-2"></i>
                    Wallet
                </a>
                <a href="{% url 'dashboard:logout' %}" class="prof list-group-item list-group-item-action d-flex align-items-center">
                    <i class="bx bx-chat fs-xl opacity-60 me-2"></i>
                    Sign Out
                </a>
                </div>
            </div>
            </div>
        </aside>

        
        {% block profile %}
            
        {% endblock profile %}
            
        </div>
    </section>
    
    <style>
        label {
        color: #fff !important;
        }
        input {
            border: none !important;
        }
        .profile-side-menu {
            background: rgb(47, 100, 143); 
            border: none;
        }
        .profile-side-menu:hover {
            background: rgb(16, 61, 97) !important;
            color: rgb(241, 237, 237) !important;
        }
        .prof:hover {
            background: transparent !important;
            color: rgb(10, 223, 165) !important;
        }
      </style>
    

{% endblock content%}
    