account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('signup/<str:ref_code>/', register, name="register"),
    path('signup/', register, name="register"),
    path('login/', login_request, name="login"), 
    path('dashboard/password-change/', security, name="security"),
    path('password_reset/', reset_password, name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html', success_url='/login/'), name='password_reset_confirm'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('account.urls', namespace='account')),
]

main/urls.py
import imp
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('privacy/', privacy, name="privacy"),
    path('terms/', terms, name="terms"),
    path('contact/', contact, name="contact"),
    path('services/', services, name="services"),
    path('plans/', plans, name="plans"),
    path('legal/', legal, name="legal"),
    path('how-to-invest/', howto, name="howto"),
] 

main/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Faq(models.Model):
    question = models.CharField(max_length=500)
    answer = models.TextField()

    def __str__(self):
        return self.question[:10]

    class Meta:
        verbose_name_plural = 'FAQ'


class Testimony(models.Model):
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=20, null=True, blank=True)
    description = models.TextField()
    image=models.ImageField(upload_to="testimonies/", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Testimonies'


class Terms(models.Model):
    heading = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name_plural = 'Terms'


# class Contact(models.Model):
#     name=models.CharField(max_length=30)
#     email=models.EmailField(max_length=30)
#     title=models.CharField(max_length=20, null=True, blank=True)
#     subject=models.TextField()

#     def __str__(self):
#         return self.name

#     class Meta:
#         verbose_name_plural = 'Contact us'


class HowTo(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'How to invest'


class Privacy(models.Model):
    description = models.TextField()

    def __str__(self):
        return self.description[:10]

    class Meta:
        verbose_name_plural = 'Privacy'


class Service(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField()
    image = models.ImageField(upload_to="services/", null=True, blank=True)

    def __str__(self):
        return self.name


class Site(models.Model):
    name = models.CharField(max_length=30, verbose_name="Site name")
    website = models.CharField(max_length=30, verbose_name="Website URL", null=True, blank=True)
    address = models.CharField(max_length=50, verbose_name="Company address")
    phone = models.CharField(max_length=20, verbose_name="Company number")
    email = models.EmailField(max_length=30, verbose_name="Company email")
    founder = models.CharField(max_length=30, verbose_name="Company founder", null=True, blank=True)
    logo = models.ImageField(upload_to="main/", null=True, blank=True)
    year = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Site features'


class About(models.Model):
    heading = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField()
    vision = models.TextField()
    mission = models.TextField()

    def __str__(self):
        return self.heading[:10]

    class Meta:
        verbose_name_plural = 'About us'

main/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse


class ContactForm(forms.Form):
    name = forms.CharField(max_length=30, required=True,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'name',
                                'placeholder': 'Name *'
                            }))
    email = forms.EmailField(max_length=30, required=True,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'email',
                                'placeholder': 'Email *'
                            }))
    subject = forms.CharField(required=True, max_length=20,
                             widget=forms.TextInput(attrs={
                                'class': 'form-control form-control-sm',
                                'id': 'subject',
                                'placeholder': 'Subject *'
                            }))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={
                                'class':'form-control form-control-sm',
                                'id': 'message',
                                'rows': 5,
                                'placeholder': 'Message *'
                            }))

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()
        name = cl_data.get('name').strip()
        email = cl_data.get('email')
        subject = cl_data.get('subject')
        # Compose mail
        message = f'{name.capitalize()} with email {email} just sent you a mail.\n'
        message += f"\nSubject: '{subject}'\n\n"
        message += cl_data.get('message')
        message += f'\n\n\nXendcoin ContactUs Page'
        message += f"\nxendcoin.com"
        # Return composed mail data
        return subject, message

    def send(self):
        subject, message = self.get_info()
        try:
            send_mail(
                subject=subject,
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=['okonkwogodspower@yahoo.com'],
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')

main/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from dashboard.models import Subscription, Withdrawal
from .forms import ContactForm

# Create your views here.
def home(request):
    sub = Subscription.objects.all()[:10]
    withdraw = Withdrawal.objects.all()[:10]
    context = {
        'sub': sub,
        'withdraw': withdraw
    }
    return render(request, 'main/index.html', context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send()
            messages.success(request, ('Thank you for contacting us. Our team will reach out to you soon.'))
            return redirect('main:contact')
    else:
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, 'main/contact.html', context)


def plans(request):
    return render(request, 'main/plans.html')

def about(request):
    return render(request, 'main/about.html')

def faq(request):
    return render(request, 'main/faq.html')

def privacy(request):
    return render(request, 'main/privacy.html')

def terms(request):
    return render(request, 'main/terms.html')

def services(request):
    return render(request, 'main/services.html')

def howto(request):
    return render(request, 'main/howto.html')

def legal(request):
    return render(request, 'main/legal.html')

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" id="top">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
        
            {% block title %}
                
            {% endblock title %}
                
        </title>

        <!-- Theme Style + Bootstrap -->
        <link rel="shortcut icon" href="{% static 'img/icon-2.png' %}">
        <link rel="stylesheet" media="screen" href="{% static 'css/theme.min.css' %}">
        <link rel="stylesheet" media="screen" href="{% static 'css/boxicons.min.css' %}">
        <link rel="stylesheet" media="screen" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" media="screen" href="{% static 'css/main.css' %}">
        

        <!-- ============================================================== -->
        <!--      This template was developed by beeLabbs tech hub          -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!--     Disclaimer: www.beeLabbs.com/terms/#disclaimer             -->
        <!-- ============================================================== -->


    </head>
    <body>
        <header class="header fixed-top">
            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a href="{% url 'main:home' %}" class="navbar-brand my-0 py-0">
                        <img src="{% static 'img/site-logo-1.png' %}" style="height: 50px;"  alt="">
                        <span style="color: rgba(10, 202, 151, 0.788); font-weight: bold;">Xendcoin</span>
                    </a>
                    <button class="navbar-toggler" type="button" 
                        data-bs-toggle="collapse" data-bs-target="#navmenu">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navmenu">
                        <ul class="navbar-nav ms-auto index">
                            <li class="nav-item">
                                <a href="{% url 'main:home' %}" class="nav-link text-light">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'main:about' %}" class="nav-link text-light">About</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="{% url 'main:services' %}" class="nav-link dropdown-toggle text-light" 
                                data-bs-toggle="dropdown" role="button" aria-haspopup="true" 
                                aria-expanded="false">Services</a>
                                <ul class="dropdown-menu text-light" style="background: rgb(1, 21, 74); border: 0;">
                                    <li>
                                        <a href="{% url 'main:services' %}" class="dropdown-item text-light">Oil & Gas</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'main:services' %}" class="dropdown-item text-light">Real Estates</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'main:services' %}" class="dropdown-item text-light">Gold</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'main:plans' %}" class="nav-link text-light">Investment</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'main:faq' %}" class="nav-link text-light">Faqs</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'main:contact' %}" class="nav-link text-light">Contact</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item mb-4 mb-md-0 mt-1 mt-md-0">
                                <a href="{% url 'account:login' %}" class="log w-1000 nav-link btn text-light btn-primary">
                                    <i class="bx bx-user fs-lg me-2"> Login</i>
                                </a>
                            </li>
                            <li class="nav-item pb-3 pb-md-0 sign-li">
                                <a href="{% url 'account:register' %}" class="sign nav-link w-100 btn text-light btn-primary">
                                    <i class="bx bx-user fs-lg me-2"> Sign Up</i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% include 'main/includes/messaging.html' %}
            <div class="px-5">
                <div class="container d-flex justify-content-center">
                    <div id="google_translate_element"></div>
                </div>
            </div>
            <!-- <div class="pt-0">
                
            </div> -->
        </header>
        
        
        <main class="page-wrapper pt-3 pt-lg-5">
                    
                    {% block content %}{% endblock %}
            
        </main>

        <!-- Footer -->
        <footer class="footer pt-5 pb-4 pb-lg-5 mt-4">
            <div class="container pt-lg-4">
                <div class="row pb-2">
                    <div class="col-lg-3 col-md-6">
                        <div class="navbar-brand text-dark p-0 me-0 mb-3 mb-lg-4">
                            <img src="{% static 'img/site-logo-1.png' %}" style="height: 50px;"  alt="">
                        <span style="color: rgba(10, 202, 151, 0.788);">Xendcoin</span>
                        </div>
                        <p class="fs-sm pb-lg-3 mb-4">
                            One of the most reliable and diversified financial investment service provider
                            in the world. With over $5.3 trillion traded daily in the market, we are 
                            dedicated to giving our clients their own share of the profit daily.
                        </p>
                    </div>
                    <div class="col-xl-8 col-lg-7 col-md-5 offset-xl-1 offset-md-1 pt-4 pt-md-1 pt-lg-0">
                        <div id="footer-links" class="row">
                            <div class="col-lg-4">
                                <h6 class="mb-2">
                                    <a href="#useful-links" class="d-block text-light dropdown-toggle d-lg-none py-2" 
                                    data-bs-toggle="collapse">Useful Links</a>
                                </h6>
                                <div id="useful-links" class="collapse d-lg-block" data-bs-parent="#footer-links">
                                    <ul class="nav flex-column pb-lg-1 mb-lg-3">
                                        <li class="nav-item"><a href="{% url 'main:home' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Home</a></li>
                                        <li class="nav-item"><a href="{% url 'main:about' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">About</a></li>
                                        <li class="nav-item"><a href="{% url 'main:services' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Our Services</a></li>
                                        <li class="nav-item"><a href="{% url 'main:plans' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Investment</a></li>
                                        <li class="nav-item"><a href="{% url 'main:howto' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">How to Invest</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3">
                                <h6 class="mb-2">
                                    <a href="#company" class="d-block text-light dropdown-toggle d-lg-none py-2" 
                                    data-bs-toggle="collapse">Company</a>
                                </h6>
                                <div id="company" class="collapse d-lg-block" data-bs-parent="#footer-links">
                                    <ul class="nav flex-column mb-2 mb-lg-0">
                                        <li class="nav-item"><a href="{% url 'main:faq' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">FAQs</a></li>
                                        <li class="nav-item"><a href="{% url 'main:terms' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Terms of Service</a></li>
                                        <li class="nav-item"><a href="{% url 'main:privacy' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Privacy Policy</a></li>
                                        <li class="nav-item"><a href="{% url 'main:legal' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Legal Info</a></li>
                                        <li class="nav-item"><a href="{% url 'main:contact' %}" 
                                            class="nav-link text-light d-inline-block px-0 pt-1 pb-2">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-xl-5 col-lg-5 col-sm-12 pt-2 pt-lg-0 px-lg-4">
                                <div class="footer-address">
                                    <h5 style="text-transform: uppercase; font-weight: 700; 
                                    color:rgb(19, 206, 193); margin-bottom: 3px;">office Address</h5>
                                    <small>26 London Lane, London, England, E8 3FU</small>
                                    
                                    <p style="padding-top: 5px;"><small style="padding-top: 4px;">+2349031795292</small><p>
                                </div>
                                <div class="footer-address footer-address2" style="padding-top: px;">
                                    <h5 style="text-transform: uppercase; font-weight: 700; 
                                    color:rgb(19, 206, 193); margin-bottom: .5px;">E-mail address</h5>
                                    <a class="text-light" href="mailto:support@beeLabbs.pro"><small>support@beeLabbs.pro</small></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr style="color:rgb(19, 206, 193);">
                <p class="nav d-block fs-xs text-center  pb-2 pb-lg-0 mb-0 mt-2">
                    &copy; beeLabbs Technologies. All Rights Reserved.
                </p>
            </div>
        </footer>
    
        <!-- <p class="btn btn-primary"><a href="#top">Top</a>
            
        </p> -->
        <!-- <button class="scroll-top scroll-to-target open"  data-target="html">
            <span style="height: 60px; width: 150px;" class="ti-angle-up"></span>
        </button> -->

        <!-- Back to top button -->
        <!-- <a href="#top" class="btn-scroll-top" data-scroll>
            <span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span>
            <i class="btn-scroll-top-icon bx bx-chevron-up"></i>
        </a> -->


        
        <!-- Vendor Scripts -->
        <script src="{% static 'js/theme.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/vanilla-tilt.min.js' %}"></script>
        <!-- <script src="{% static 'js/wow.min.js' %}"></script> -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/smooth-scroll.polyfills.min.js' %}"></script>
        <script type="text/javascript">
            function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
            }
        </script>
        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        
    </body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

        {% block title %}
        Xendcoin - Enquiries
        {% endblock title %}

        {% block content %}
            <section class="px-lg-5 px-1" style="padding-top: 10em;">
                <div class="container">
                    <h1 class="text-center mb-lg-5 mb-3">
                        Contact <span style="color: rgb(10, 223, 165);">Us</span>
                    </h1>
                    <div class="row px-lg-5">
                        <div class="col-md-6 px-lg-5">
                            <p class="text-light" style="line-height: 1.8; text-align: justify;">
                                Do you have any questions? We recommend that you start searching 
                                for the necessary information in the <a style="text-decoration: none;" href="{% url 'main:faq' %}">
                                    <span style="color: rgb(10, 223, 165);">FAQ</span></a> 
                                section. If you do not find the information you need, contact 
                                beeLabbs support through the form below. Our team will 
                                reach out to you within 24 hours.
                            </p>
                            <!-- <br> -->
                            <div class="footer-address">
                                <h5 class="mt-lg-5 mt-4 mb-1" style="text-transform: uppercase; font-weight: 700; color:rgb(19, 206, 193); ">our headquarters</h5>
                                <small class="text-muted">26 London Lane, London, England, E8 3FU</small>
                                
                                <p><small class="text-muted" style="padding-top: 4px;">+2349031795292</small><p>
                            </div>
                            <div class="footer-address footer-address2" style="padding-top: px;">
                                <h5 class="mb-1" style="text-transform: uppercase; font-weight: 700; color:rgb(19, 206, 193);">E-mail address</h5>
                                <a class="text-muted" href="mailto:support@beeLabbs.pro"><small>support@beeLabbs.pro</small></a>
                            </div>
                        </div>
                        <div class="col-md-6 px-lg-5 mt-lg-0 mt-5">
                            <div class="contact">
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <!-- Name -->
                                    <div>
                                        {{ form.name }}
                                        <label class="form-label fs-xs" for="name"></label>
                                    </div>
                                    <!-- Email -->
                                    <div>
                                        {{ form.email }}
                                        <label class="form-label fs-xs" for="email"></label>
                                    </div>
                                    <!-- Subject -->
                                    <div>
                                        {{ form.subject }}
                                        <label class="form-label fs-xs" for="subject"></label>
                                    </div>
                                    <!-- Message -->
                                    <div class="">
                                        {{ form.message }}
                                        <label class="form-label fs-xs" for="message"></label>
                                    </div>
                                    <div>
                                        <button class="btn btn-outline-primary" type="submit">Send Message</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <style>
                    .contact input {
                        height: 50px !important;
                    }
                    .contact .btn-outline-primary {
                        border-radius: 5px;
                        /* border: 0; */
                        padding: 7px 30px;
                    }
                    .contact .btn-outline-primary:hover {
                        background: linear-gradient(to right, rgb(38, 170, 249) 
                            0%, rgb(19, 206, 193) 100%);
                        border: 0;
                        border: 2px solid rgb(0, 22, 97);
                    }
                    .contact input, textarea {
                        font-size: 14px !important;
                        color: #000 !important;
                    }
                </style>
            </section>
        {% endblock %}

main/templates/main/legal.html
{% extends 'main/base.html' %}
    {% load static %}

    {% block title %}
    Xendcoin - Legal information
    {% endblock title %}

    {% block content %}
        <section class="privacy px-lg-5 px-1" style="padding-top: 10em;">
            <div class="container">
                <h1 class="text-center text-light mb-lg-5 mb-3">
                    <span style="color: rgb(10, 223, 165);">Legal </span>Information
                </h1>
                <div class="row">
                    <div class="col-lg-7 px-lg-3">
                        <p style="text-align: justify;">
                            Xandcoin is one of the most reliable diversified financial investment service provider in the world.
                            Our fundamental mission is to help customers and clients achieve their financial objectives. With offices 
                            in United States and our headquarters in England, Xandcoin have active staffs with over 25 years of experience
                            in managing finances and a strong knowledge of the crypto space. We are committed to pushing the boundaries of
                            what constitutes the highest standards in trade and asset management.
                        </p>
                        <p style="text-align: justify;">
                            Today, as a successful trade investment and asset management company, we are trusted by thousands of clients.
                            Our sterling reputation, dedication to meeting our clients' needs and innovative approach to business development
                            are some driving forces behind our success. Xandcoin has one of the world's largest independent traders and fund 
                            managers with clients from different parts of the world.
                        </p>
                    </div>
                    <div class="col-lg-5 px-2 px-lg-5">
                        <!-- <p><b>Legal Certificate</b></p> -->
                        <img src="{% static 'img/xandcoin-cert.jpg' %}" alt="" style="height: 90%; width: 100%; border-radius: 5px;">
                        <a class="btn btn-sm btn-primary w-100 mt-2" style="border-radius: 5px; font-size: 14px;"
                        href="{% static 'img/xandcoin-cert.jpg' %}">
                            Download Certificate
                        </a>
                    </div>
                </div>
            </div>
        </section>
    {% endblock %}

main/templates/main/services.html
{% extends 'main/base.html' %}

{% block title %}
    Xendcoin - Services
{% endblock title %}